const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=__dirname;const envPath=path.join(root,'.env.openrouter.local');if(fs.existsSync(envPath))for(const line of fs.readFileSync(envPath,'utf8').split('\n')){const at=line.indexOf('=');if(at>0&&!process.env[line.slice(0,at)])process.env[line.slice(0,at)]=line.slice(at+1).trim()}
const system=`你是“慢慢来”，温暖、简洁的日常教程陪做助手。用简体中文。首先识别用户的具体对象和真实意图，不要一上来按教程详细程度分类。比如“第一次给绿植换盆”，先问是哪种植物，列举绿萝/龟背竹、多肉/仙人掌、兰花等实际品类；允许用户不知道品种。已知品种后再确认换盆原因和当前状态。每轮只问一个最必要的问题，不要一次列举大量问题、分类或答案。等待用户自由输入后继续。回复通常控制在2至4句，用户明确要求步骤时才展开详细内容。不重复问已知信息。澄清充分后按材料、具体操作、完成标准、可能错误和补救提供指导。你没有联网检索工具，也不能看用户上传的视频或图片；绝不能声称已检索、看过视频，或编造视频标题、链接、时间戳。可提供检索关键词并说明暂未连接视频库。用户要求直接给步骤时可给通用指导，但标明不是视频解析。遇到未知材料/植物时不要作确定性判断。只返回直接给用户看的中文正文，不要输出 JSON、字段名或代码围栏。`;

function parseReply(content){
 let text=content.trim().replace(/^\x60{3}(?:json)?\s*/i,'').replace(/\s*\x60{3}$/,'');
 for(let i=0;i<3;i++){try{const parsed=JSON.parse(text);if(typeof parsed==='string'){text=parsed;continue}if(parsed&&typeof parsed.message==='string'){text=parsed.message;continue}return null}catch{break}}
 if(/^\s*\{/.test(text)||/^\s*\x60{3}/.test(text))return null;
 return {message:text,options:[]};
}

let busy=false;const reply=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))};
http.createServer(async(req,res)=>{if(req.method==='POST'&&req.url==='/api/chat'){if(req.headers.origin&&req.headers.origin!==`http://${req.headers.host}`)return reply(res,403,{error:'不允许跨站请求'});if(busy)return reply(res,429,{error:'上一条还在回答，请稍等'});let raw='';try{for await(const chunk of req){raw+=chunk;if(raw.length>60000)return reply(res,413,{error:'对话过长，请开启新对话'})}const body=JSON.parse(raw);if(!Array.isArray(body.messages)||!body.messages.length)throw Error('输入格式不正确');const messages=body.messages.slice(-12).map(m=>{if(!['user','assistant'].includes(m.role)||typeof m.content!=='string'||m.content.length>6000)throw Error('消息格式或长度不正确');return {role:m.role,content:m.content}});if(!process.env.OPENROUTER_API_KEY)return reply(res,503,{error:'服务端尚未配置密钥'});busy=true;const upstream=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:'Bearer '+process.env.OPENROUTER_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:'inclusionai/ling-3.0-flash-sante:free',messages:[{role:'system',content:system},...messages],max_tokens:900,temperature:0.4,stream:false}),signal:AbortSignal.timeout(55000)});if(!upstream.ok){let providerFailure={};try{providerFailure=await upstream.json()}catch{}const sharedPool=providerFailure.error?.metadata?.limit_source==='upstream_provider_shared_pool';console.error('Provider HTTP',upstream.status,'shared_pool',sharedPool);return reply(res,upstream.status===429?429:502,{error:upstream.status===429?(sharedPool?'免费模型的上游共享额度池正在限流，暂时无法生成回复。请稍后再试；这不是你的输入问题。':'模型请求受限（429），请稍后再试。'):'模型服务返回 '+upstream.status+'，请检查密钥权限、余额和模型名称。'})}const data=await upstream.json();const content=data.choices?.[0]?.message?.content;if(!content)throw Error('模型未返回内容');let result=parseReply(content);if(!result)return reply(res,502,{error:'模型回复格式不完整，请重试。'});reply(res,200,{message:result.message,options:Array.isArray(result.options)?result.options.filter(x=>typeof x==='string').slice(0,4):[]})}catch(e){reply(res,502,{error:e.name==='TimeoutError'?'回答超时，请重新发送。':'请求失败，请稍后重试。'})}finally{busy=false}return}if(req.method!=='GET'||!['/','/index.html'].includes(req.url.split('?')[0])){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});fs.createReadStream(path.join(root,'dist/index.html')).pipe(res)}).listen(8766,'127.0.0.1',()=>console.log('Local demo: http://127.0.0.1:8766'));
